#!/bin/bash
# This script runs on the host machine in which the disk image builder is running 
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo "JENKINS ssh key path $JENKINS_PUBLIC_SSH_KEY_PATH"
echo "JENKINS ssh key real path "
echo "$(realpath $JENKINS_PUBLIC_SSH_KEY_PATH)"
JENKINS_PUBLIC_SSH_KEY_PATH="${JENKINS_PUBLIC_SSH_KEY_PATH:-/home/jenkins/.ssh/id_rsa.pub}"

if [ ! -f "${JENKINS_PUBLIC_SSH_KEY_PATH}" ]; then
    die "Can not find the public key for the jenkins user."
fi

# TMP_HOOKS_PATH is the shared directory whose files get copied to the image being build.
cp "${JENKINS_PUBLIC_SSH_KEY_PATH}" "${TMP_HOOKS_PATH}/jenkins-public-ssh-key"
