#!/usr/bin/env python
"""
This is a python executable that is used from ``builder.sh``.
This file when called with an openstack image id as parameter,
will output the latest image id of the given image name.
"""
from __future__ import print_function
import time
import os
import sys

from glanceclient import Client
from keystoneauth1 import loading, session

if len(sys.argv) < 2:
    raise Exception('Usage py_get_image_id <image_name>')

# Configures the python script to use open stack configurations.
LOADER = loading.get_plugin_loader('password')
AUTH = LOADER.load_from_options(
    auth_url=os.environ['OS_AUTH_URL'],
    username=os.environ['OS_USERNAME'],
    password=os.environ['OS_PASSWORD'],
    project_id=os.environ['OS_TENANT_ID']
)

SESSION = session.Session(auth=AUTH)
GLANCE = Client('2', session=SESSION)
# Zip the image ids and the timestamp together.
# The `image['id']` is corresponding to the
# image name ``sys.argv[1]``.
IMAGES = [
    (
        image['id'],
        time.mktime(time.strptime(image['updated_at'], '%Y-%m-%dT%H:%M:%SZ'))
    )
    for image in GLANCE.images.list()
    if image['name'] == sys.argv[1]
]
# Get the latest image
sorted(IMAGES, key=lambda x: x[1])
print(IMAGES[-1][0])
