[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[project]
name = "pulp-sec"
version = "0.1.0"
description = "Scripts to inspect software security in Pulp supported branches."
readme = "README.md"
authors = [
    { name = "Matthias Dellweg", email = "mdellweg@redhat.com" }
]
requires-python = ">=3.14"
dependencies = [
    "packaging>=26.3",
    "pydantic-settings>=2.14.2",
    "pyyaml>=6.0.3",
]
classifiers =[
    "Private :: Do Not Upload",
]

[project.scripts]
pulp-sec = "pulp_sec:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.1",
    "ty>=0.0.69",
]
