#!/bin/bash
# This script will set the boot parameters for FIPS image building
# This script will get the UUID of the boot filesystem and append that information with the fips flag to the
# bootloader commandline for FIPS to be enabled.

IS_FIPS="${IS_FIPS:-false}"
if [ "${IS_FIPS}" = true ];then
    echo "Setting up Fips environment"
    dracut --force
    grubby --update-kernel=DEFAULT --args="boot=UUID=$(findmnt /boot -o UUID)"
fi

