name    'pulp-pulp'
version '0.2.1'
source 'https://github.com/pulp_packaging/puppet/pulp'
author 'Pulp'
license 'GPL, Version 2.0'
summary 'This module can be used to install and configure Pulp servers, consumers, and nodes.'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>=3.2.0'
