---
- block:
  - name: Open firewall ports (iptables)
    iptables:
      action: insert
      chain: INPUT
      ctstate: NEW
      protocol: "{{ item.protocol }}"
      destination_port: "{{ item.port }}"
      jump: ACCEPT
    with_items:
      - { port: 'http', protocol: 'tcp' }
      - { port: 'https', protocol: 'tcp' }
      - { port: 'amqps', protocol: 'tcp' }
      - { port: 'amqp', protocol: 'tcp' }
    notify:
      - Save IPv4 iptables configuration

  - name: Install required packages for RHEL
    action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
    with_items:
        - libselinux-python
        - policycoreutils-python
        - attr

  - name: Setup qpid custom repo
    get_url: url=https://copr.fedorainfracloud.org/coprs/g/qpid/qpid/repo/epel-6/irina-qpid-epel-6.repo dest=/etc/yum.repos.d/copr-qpid.repo

  - name:  Allow Apache to listen on tcp port 5000
    seport:
      ports: 5000
      proto: tcp
      setype: http_port_t
      state: present
  when:
      - (ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 6)

- block:
  - name: Install firewalld and python bindings
    action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
    with_items:
      - firewalld
      - python-firewall

  - name: Start and enable firewalld
    service: name=firewalld state=started enabled=yes

  - name: Open firewall ports (firewalld)
    firewalld:
      port: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    with_items:
      # As of this writing, firewalld knows about a miniscule number of services
      # out of the box. `firewall-cmd --get-services | wc -w` returns "103", and
      # the list of services doesn't include amqp or amqps, among many others.
      # Thus, we have to explicitly write out port/transport pairs here.
      - "80/tcp"   # http
      - "443/tcp"  # https
      - "5671/tcp" # amqps
      - "5672/tcp" # amqp

  when:
    - not (ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 6)

- name: Install MongoDB server
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - mongodb-server
    - mongodb

- name: Start and enable MongoDB server service
  service: name=mongod state=started enabled=yes

- name: Install qpid-cpp server
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - qpid-cpp-server
    - qpid-cpp-server-linearstore

- name: Install python-saslwrapper
  action: "{{ ansible_pkg_mgr }} name=python-saslwrapper state=latest"
  when: ansible_os_family == "RedHat"

- name: Start and enable qpid-cpp server service
  service: name=qpidd state=started enabled=yes

- name: Explicitly install python-django (https://bugzilla.redhat.com/show_bug.cgi?id=1524560)
  action: "{{ ansible_pkg_mgr }} name=python-django state=latest"
  when:  (ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 7)

- name: Setup Pulp nightly repository
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
  with_dict:
    pulp:
      name: Pulp Project repository
      baseurl: "https://repos.fedorapeople.org/pulp/pulp/testing/automation/{{ pulp_version }}/stage/{% if ansible_distribution == 'Fedora' %}fedora-{% endif %}$releasever/$basearch/"

      gpgcheck: 0
  when: pulp_build == "nightly"

- name: Setup Pulp nightly koji repository
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
  with_dict:
    pulp:
      name: Pulp Project repository
      baseurl: "http://koji.katello.org/releases/yum/pulp-nightly/pulp/{% if ansible_distribution == 'Fedora' %}fedora-{% endif %}$releasever/$basearch/"
      gpgcheck: 0
  when: pulp_build == "nightly_koji"

- name: Setup Pulp beta or stable repository
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
  with_dict:
    pulp:
      name: Pulp Project repository
      baseurl: "https://repos.fedorapeople.org/pulp/pulp/{{ pulp_build }}/{{ pulp_version }}/{% if ansible_distribution == 'Fedora' %}fedora-{% endif %}$releasever/$basearch/"
      gpgcheck: 0
  when: pulp_build == "beta" or pulp_build == "stable"

# https://github.com/ansible/ansible/issues/26868
- block:
  - name: Install Pulp Server (Fedora 26)
    command: dnf -y install @pulp-server-qpid
    notify:
      - Restart Apache service
      - Restart Pulp workers service
      - Restart Pulp celerybeat service
      - Restart Pulp resource manager service

  - name: Install Pulp Admin (RPM, Puppet, Docker) (Fedora 26)
    command: dnf -y install @pulp-admin

  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version|int == 26)

- block:
  - name: Install Pulp Server
    action: "{{ ansible_pkg_mgr }} name=@pulp-server-qpid"
    notify:
      - Restart qpidd service
      - Restart Apache service
      - Restart Pulp workers service
      - Restart Pulp celerybeat service
      - Restart Pulp resource manager service

  - name: Install Pulp Admin (RPM, Puppet, Docker)
    action: "{{ ansible_pkg_mgr }} name=@pulp-admin"

  when: not (ansible_distribution == "Fedora" and ansible_distribution_major_version|int == 26)

- name: Install OSTree
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - pulp-ostree-plugins
    - pulp-ostree-admin-extensions
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 7) or
        (ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 23)

- name: Install Pulp Python plugin
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - pulp-python-plugins
    - pulp-python-admin-extensions
  notify:
    - Restart Apache service

- name: Configure pulp-admin
  shell: "sudo sed -i 's/# verify_ssl: True/verify_ssl: False/g' /etc/pulp/admin/admin.conf"

- name: Generate RSA key pair
  shell: "sudo pulp-gen-key-pair"
  when: pulp_version | version_compare('2.13', '>=')

- name: Generate SSL CA certificate
  shell: "sudo pulp-gen-ca-certificate"
  when: pulp_version | version_compare('2.13', '>=')

- name: Check if Pulp's DB was initialized
  stat:
    path: /var/lib/pulp/db_initialized.flag
  register: db_init

- name: Initialize Pulp's DB
  shell: sudo -u apache pulp-manage-db && touch /var/lib/pulp/db_initialized.flag
  notify:
    - Restart Apache service
    - Restart Pulp workers service
    - Restart Pulp celerybeat service
    - Restart Pulp resource manager service
  when: not db_init.stat.exists

- name: Enable pulp_manage_rsync SELinux boolean
  shell: sudo semanage boolean --modify --on pulp_manage_rsync
  when: pulp_version | version_compare('2.10', '>=')

- name: Ensure Apache server is started
  service:
    name: httpd
    enabled: yes
    state: started

- name: Ensure Pulp workers are started
  service:
    name: pulp_workers
    enabled: yes
    state: started

- name: Ensure Pulp celerybeat is started
  service:
    name: pulp_celerybeat
    enabled: yes
    state: started

- name: Ensure Pulp resource manager is started
  service:
    name: pulp_resource_manager
    enabled: yes
    state: started
