---
- name: Install MongoDB server
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - mongodb-server
    - mongodb

- name: Start and enable MongoDB server service
  service: name=mongod state=started enabled=yes

- name: Setup qpid custom repo
  get_url: url=https://copr.fedorainfracloud.org/coprs/g/qpid/qpid/repo/epel-6/irina-qpid-epel-6.repo dest=/etc/yum.repos.d/copr-qpid.repo
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

- name: Install qpid-cpp server
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - qpid-cpp-server
    - qpid-cpp-server-linearstore

- name: Start and enable qpid-cpp server service
  service: name=qpidd state=started enabled=yes

- name: Setup Pulp nightly repository
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
  with_dict:
    pulp:
      name: Pulp Project repository
      baseurl: "https://repos.fedorapeople.org/pulp/pulp/testing/automation/{{ pulp_version }}/stage/{% if ansible_distribution == 'Fedora' %}fedora-{% endif %}$releasever/$basearch/"

      gpgcheck: 0
  when: pulp_build == "nightly"

- name: Setup Pulp beta or stable repository
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
  with_dict:
    pulp:
      name: Pulp Project repository
      baseurl: "https://repos.fedorapeople.org/pulp/pulp/{{ pulp_build }}/{{ pulp_version }}/{% if ansible_distribution == 'Fedora' %}fedora-{% endif %}$releasever/$basearch/"
      gpgcheck: 0
  when: pulp_build == "beta" or pulp_build == "stable"

- name: Install Pulp Server
  action: "{{ ansible_pkg_mgr }} name=@pulp-server-qpid"
  notify:
    - Restart Apache service
    - Restart Pulp workers service
    - Restart Pulp celerybeat service
    - Restart Pulp resource manager service

- name: Install Pulp Admin (RPM, Puppet, Docker)
  action: "{{ ansible_pkg_mgr }} name=@pulp-admin"

- name: Install OSTree
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - pulp-ostree-plugins
    - pulp-ostree-admin-extensions
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 7) or
        (ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 23)

- name: Install Pulp Python plugin
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - pulp-python-plugins
    - pulp-python-admin-extensions
  notify:
    - Restart Apache service

- name: Configure pulp-admin
  shell: "sudo sed -i 's/# verify_ssl: True/verify_ssl: False/g' /etc/pulp/admin/admin.conf"

- name: Check if Pulp's DB was initialized
  stat:
    path: /var/lib/pulp/db_initialized.flag
  register: db_init

- name: Initialize Pulp's DB
  shell: sudo -u apache pulp-manage-db && touch /var/lib/pulp/db_initialized.flag
  notify:
    - Restart Apache service
    - Restart Pulp workers service
    - Restart Pulp celerybeat service
    - Restart Pulp resource manager service
  when: not db_init.stat.exists

- name: Ensure Apache server is running
  service:
    name: httpd
    enabled: yes
    state: running

- name: Ensure Pulp workers are running
  service:
    name: pulp_workers
    enabled: yes
    state: running

- name: Ensure Pulp celerybeat is running
  service:
    name: pulp_celerybeat
    enabled: yes
    state: running

- name: Ensure Pulp resource manager is running
  service:
    name: pulp_resource_manager
    enabled: yes
    state: running
